export const heroesActionType = {
  SET_CURRENT_DATA: "SET_CURRENT_DATA",
  ADD_FAVORITES: "ADD_FAVORITES",
  REMOVE_FAVORITES: "REMOVE_FAVORITES",
  NEXT_PAGE: "NEXT_PAGE",
  SEARCH_EPISODE: "SEARCH_EPISODE",
  SEARCH_GENDER: "SEARCH_GENDER",
  SEARCH_STATUS: "SEARCH_STATUS",
  SEARCH_SPECIES: "SEARCH_SPECIES",
  SORT_BY_NAME: "SORT_BY_NAME",
  SORT_BY_STATUS: "SORT_BY_STATUS",
  SHOW_MORE: "SHOW_MORE",
};
