export const EpisodesActionType = {
  SET_CURRENT_DATA: "SET_CURRENT_DATA",
  ADD_FAVORITES: "ADD_FAVORITES",
  REMOVE_FAVORITES: "REMOVE_FAVORITES",
  NEXT_PAGE: "NEXT_PAGE",
  SEARCH_EPISODE: "SEARCH_EPISODE",
  SORT_BY_NAME: " SORT_BY_NAME",
  SORT_BY_TIME: "SORT_BY_TIME",
  SHOW_MORE: "SHOW_MORE",
  SET_HERO_LIST: "SET_HERO_LIST",
};
