export const EpisodesActionType = {
  SET_CURRENT_DATA: "SET_CURRENT_DATA",
  ADD_FAVORITES: "ADD_FAVORITES",
  REMOVE_FAVORITES: "REMOVE_FAVORITES",
  NEXT_PAGE: "NEXT_PAGE",
  SEARCH_EPISODE: "SEARCH_EPISODE",
  SORT_BY_NAME: " SORT_BY_NAME",
};
